# GitHub Pages Configuration
title: Huzaifa Tariq
description: Economics, Data Analytics, and Essays
author: M. Huzaifa Tariq

# Markdown settings
markdown: kramdown

# Exclude from processing
exclude:
  - README.md
  - LICENSE
